// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title BasePaymentGateway - USDC Payment Router on Base
/// @notice Non-custodial: transfers USDC directly from the buyer to the admin
///         wallet using transferFrom (requires prior approve from the buyer).
/// @dev Designed for Base Mainnet. USDC has 6 decimals on Base.

// Minimal ERC20 interface to interact with USDC
interface IERC20 {
    function transferFrom(address sender, address recipient, uint256 amount) external returns (bool);
    function allowance(address owner, address spender) external view returns (uint256);
}

contract BasePaymentGateway {
    // ─── State ───────────────────────────────────────────────────────
    address public immutable owner;
    IERC20  public immutable usdc;

    /// @notice Tracks which orderIds have already been paid (replay protection)
    mapping(string => bool) public orderFulfilled;

    // ─── Events ──────────────────────────────────────────────────────
    /// @notice Emitted when a payment is successfully processed.
    ///         Your web2 backend should listen for this event to fulfill the order.
    /// @param buyer   Address of the buyer who paid
    /// @param orderId Unique order identifier (generated by your web app)
    /// @param amount  Amount in USDC (6 decimals). E.g.: 10 USDC = 10_000_000
    event PaymentReceived(
        address indexed buyer,
        string  orderId,
        uint256 amount
    );

    // ─── Custom errors (saves gas vs require with string) ────────────
    error ZeroAmount();
    error EmptyOrderId();
    error OrderAlreadyPaid(string orderId);
    error InsufficientAllowance(uint256 required, uint256 actual);
    error TransferFailed();

    // ─── Constructor ─────────────────────────────────────────────────
    /// @param _usdcAddress Address of the USDC contract on Base
    ///        Base Mainnet: 0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913
    ///        Base Sepolia: 0x036CbD53842c5426634e7929541eC2318f3dCF7e
    constructor(address _usdcAddress) {
        owner = msg.sender;
        usdc  = IERC20(_usdcAddress);
    }

    // ─── Main function ───────────────────────────────────────────────
    /// @notice Processes an order payment. The buyer must have called
    ///         approve() on USDC for at least `amount` before calling this.
    /// @param amount  Amount to charge in USDC smallest units (6 decimals)
    /// @param orderId Unique order identifier
    function payForOrder(uint256 amount, string calldata orderId) external {
        // ── Checks ──────────────────────────────────────────────
        if (amount == 0) revert ZeroAmount();
        if (bytes(orderId).length == 0) revert EmptyOrderId();
        if (orderFulfilled[orderId]) revert OrderAlreadyPaid(orderId);

        uint256 allowed = usdc.allowance(msg.sender, address(this));
        if (allowed < amount) {
            revert InsufficientAllowance(amount, allowed);
        }

        // ── Effects (state changes BEFORE external call — CEI pattern) ──
        orderFulfilled[orderId] = true;
        emit PaymentReceived(msg.sender, orderId, amount);

        // ── Interactions (external call LAST) ───────────────────
        bool success = usdc.transferFrom(msg.sender, owner, amount);
        if (!success) revert TransferFailed();
    }

    // ─── Convenience view ────────────────────────────────────────────
    /// @notice Checks how much USDC a user has approved for this contract
    /// @param user Address of the user to query
    /// @return Amount approved in USDC smallest units
    function checkAllowance(address user) external view returns (uint256) {
        return usdc.allowance(user, address(this));
    }
}
